
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= Rails.application.secrets[:database][:host] %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  database: sustain_development
  reaping_frequency: 30

test:
  <<: *default
  host: <%= Rails.application.secrets[:database][:host] %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  database: sustain_test
  reaping_frequency: 30

production:
  url: <%= ENV['DATABASE_URL'] %>

